export const ADD_JOKE = 'APP/ADD_JOKE';
export const SAVE_DOWN_JOKE = 'APP/SAVE_DOWN_JOKE';
export const DELETE_SAVED_JOKE = 'APP/DELETE_SAVED_JOKE';
export const DELETE_JOKE = 'APP/DELETE_JOKE';
export const SAVE_EDITED_JOKE = 'APP/SAVE_EDITED_JOKE';
export const GET_CATEGORIES = 'APP/GET_CATEGORIES';